#!/usr/bin/python3

import sys
import os.path

name = sys.argv[1]

header = """// 
// YASE %s Module Header
// 
// Copyright (C) 2022 Eric Klavins
// This file is part of YASE
// 
// YASE is free software: you can redistribute it and/or modify it under the
// terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version.
//
// YASE is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
// FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
// details.
// 
// You should have received a copy of the GNU General Public License along
// with YASE. If not, see <https://www.gnu.org/licenses/>.
// 

#ifndef YASE_%s_H
#define YASE_%s_H

#include "yase.hh"

namespace yase {

    class %s : public Module {

    public:

      %s();
      void init();
      void update();

    private:

    };

}

#endif
""" % (name, name.upper(), name.upper(), name, name)

source = """// 
// YASE %s Module Implementation
// 
// Copyright (C) 2022 Eric Klavins
// This file is part of YASE
// 
// YASE is free software: you can redistribute it and/or modify it under the
// terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version.
//
// YASE is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
// FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
// details.
// 
// You should have received a copy of the GNU General Public License along
// with YASE. If not, see <https://www.gnu.org/licenses/>.
// 

#include "%s.hh"
#include "yase.hh"

namespace yase {

  %s::%s() {

  }

  void %s::init() {

  }

  void %s::update() {

  }    

}

""" % (name, name.lower(),name,name,name,name)

if not os.path.exists("include/%s.hh" % name.lower()):
    header_file = open("include/%s.hh" % name.lower(), "w")
    header_file.write(header)
    header_file.close()
else:
  print("Header file already exists ... skipping")

if not os.path.exists("src/%s.cc" % name.lower()):
    source_file = open("src/%s.cc" % name.lower(), "w")
    source_file.write(source)
    source_file.close()
else:
  print("Source file already exists ... skipping")    